spring.application.name=APIGateway

server.port=8084

spring.cloud.gateway.routes[0].id=QUIZSERVICE
spring.cloud.gateway.routes[0].url=lb://QUIZSERVICE
spring.cloud.gateway.routes[0].predicates[0]=path= /quiz/**

spring.cloud.gateway.routes[1].id=QUESTIONSERVICE
spring.cloud.gateway.routes[1].url=lb://QUESTIONSERVICE
spring.cloud.gateway.routes[1].predicates[0]=path= /question/**